POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRoaGQiLCJpZCI6IjYzOWVkYjA4ZDAxMjg4ZTUzMDU1MGVjZSIsImlhdCI6MTY3MTM2MDY1M30.POA9OGkTwXp-QOf7fAE0qnkfvBSLmMl28y1EhMnMsxI

{
"title": "NEWBLOGTEST10",
"author": "USER",
"url": "USERASSOSIAATIOTEST10",
"likes": 1234567
}

# {
#     "username":"dhhd",
#     "name":"fsdf",
#     "password": "suhjh"
# }